### ISSUE TITLE
Store More Subject Data for Enhanced Context Tracking

### ISSUE THREAD

**Issue by Daniel061** [Daniel061/Sophie6.1#39]
Currently only a subject word is stored and can be referred back to.

In order for more precise context tracking, more data will be needed, such as adjectives and nouns associated with the subject. The original string the subject was used in. The indirect object of that string if it has one. Contraction break down if the subject happens to be a contraction. The gender of the subject if it's a proper noun and etc.

I propose a SubjectData class to handle any and all data associated with the subject. Much like the MemoryCells class is handled by c_Lobes.h class, this new SubjectData class can be handled by c_SubjectStack.h class in a Map container. 

After implementation of the new SubjectData class, a file storage and retrieval method will have to be created.

Steps need:

- [x] Create a class that can be copied in a map for lookup and reference.
- [x] Test
- [x] Add the functions to set and retrieve the data.
- [x] Test
- [x] Improve SetSubject function to use the new class.
- [x] Test
- [ ] Add code for Question Handler to reference the new subject data.
- [ ] Test
- [ ] Add code for other routines to check with the extra subject data.
- [ ] Test
- [ ] Add code for pronoun references to look back to subject and inquire about gender.
- [ ] Test
- [ ] Save the Subject Data flow in a file.
- [ ] Test
- [ ] Read the Subject Data flow on start up.
- [ ] Test
